
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../features/reports/providers/report_providers.dart';
import '../core/utils/currency_formatter.dart';
import 'calculation_engine.dart';

class PDFService {
  static const PdfColor primaryColor = PdfColor.fromInt(0xFF003B1B);
  static const PdfColor secondaryColor = PdfColor.fromInt(0xFFFEA619);
  static const PdfColor surfaceColor = PdfColor.fromInt(0xFFF8FAF4);
  static const PdfColor textColor = PdfColor.fromInt(0xFF191C19);

  static Future<void> generateFinancialReport({
    required String farmName,
    required String ownerName,
    required FarmSummaryFinancials summary,
    required List<BatchPerformanceRow> batches,
    required List<BatchFinancials> detailedBatches,
  }) async {
    final pdf = pw.Document(
      title: '$farmName - Financial Report',
      author: 'AgroPrecision',
    );

    // Cover Page
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => _buildCoverPage(farmName, ownerName),
      ),
    );

    // Summary Page
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        header: (context) => _buildHeader(farmName),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildSectionTitle('Executive Summary'),
          _buildSummaryGrid(summary),
          pw.SizedBox(height: 30),
          _buildSectionTitle('Batch Performance Overview'),
          _buildBatchTable(batches),
        ],
      ),
    );

    // Detailed Pages
    for (final batch in detailedBatches) {
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          header: (context) => _buildHeader(farmName),
          footer: (context) => _buildFooter(context),
          build: (context) => [
            _buildBatchHeader(batch),
            pw.SizedBox(height: 20),
            _buildBatchDetails(batch),
            pw.SizedBox(height: 20),
            _buildExpenseTable(batch),
          ],
        ),
      );
    }

    final Uint8List bytes = await pdf.save();
    final sanitizedFarmName = farmName.replaceAll(RegExp(r'[<>:"/\\|?*]'), '_');
    
    await Printing.sharePdf(
      bytes: bytes,
      filename: '${sanitizedFarmName}_Report_${DateFormat('yyyyMMdd').format(DateTime.now())}.pdf',
    );
  }

  static pw.Widget _buildCoverPage(String farmName, String ownerName) {
    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: primaryColor, width: 2),
      ),
      padding: const pw.EdgeInsets.all(40),
      child: pw.Column(
        mainAxisAlignment: pw.MainAxisAlignment.center,
        children: [
          pw.Divider(color: secondaryColor, thickness: 5),
          pw.SizedBox(height: 40),
          pw.Text('AGROPRECISION',
              style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                  letterSpacing: 5,
                  color: secondaryColor)),
          pw.SizedBox(height: 20),
          pw.Text(farmName.toUpperCase(),
              textAlign: pw.TextAlign.center,
              style: pw.TextStyle(
                  fontSize: 36,
                  fontWeight: pw.FontWeight.bold,
                  color: primaryColor)),
          pw.SizedBox(height: 10),
          pw.Text('FINANCIAL PERFORMANCE REPORT',
              style: pw.TextStyle(
                  fontSize: 18,
                  letterSpacing: 2,
                  color: PdfColors.grey700)),
          pw.SizedBox(height: 80),
          pw.Container(height: 2, width: 100, color: secondaryColor),
          pw.SizedBox(height: 40),
          pw.Text('PREPARED FOR',
              style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey500)),
          pw.Text(ownerName,
              style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                  color: primaryColor)),
          pw.SizedBox(height: 20),
          pw.Text(DateFormat('MMMM dd, yyyy').format(DateTime.now()),
              style: pw.TextStyle(fontSize: 14, color: PdfColors.grey600)),
          pw.Spacer(),
          pw.Text('Confidential Report • Generated by Poultry Path Engine',
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
        ],
      ),
    );
  }

  static pw.Widget _buildHeader(String farmName) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 10),
      margin: const pw.EdgeInsets.only(bottom: 20),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: secondaryColor, width: 0.5)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(farmName,
              style: pw.TextStyle(
                  color: primaryColor,
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 12)),
          pw.Text('Financial Report',
              style: pw.TextStyle(color: PdfColors.grey, fontSize: 10)),
        ],
      ),
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 20),
      padding: const pw.EdgeInsets.only(top: 10),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey200, width: 0.5)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by AgroPrecision',
              style: pw.TextStyle(color: PdfColors.grey, fontSize: 8)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(color: PdfColors.grey, fontSize: 8)),
        ],
      ),
    );
  }

  static pw.Widget _buildSectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 15),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title.toUpperCase(),
              style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                  color: primaryColor,
                  letterSpacing: 1.2)),
          pw.Container(height: 2, width: 30, color: secondaryColor),
        ],
      ),
    );
  }

  static pw.Widget _buildSummaryGrid(FarmSummaryFinancials summary) {
    return pw.Row(
      children: [
        _buildStatCard('Total Profit',
            CurrencyFormatter.format(summary.totalProfit), primaryColor),
        pw.SizedBox(width: 10),
        _buildStatCard('Overall ROI', '${summary.overallROI.toStringAsFixed(1)}%',
            secondaryColor),
        pw.SizedBox(width: 10),
        _buildStatCard('Avg. Cost/Bird',
            CurrencyFormatter.format(summary.avgCostPerBird), PdfColors.blueGrey700),
      ],
    );
  }

  static pw.Widget _buildStatCard(String label, String value, PdfColor color) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(15),
        decoration: pw.BoxDecoration(
          color: PdfColors.grey100,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
          border: pw.Border.all(color: PdfColors.grey200),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(label.toUpperCase(),
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
            pw.SizedBox(height: 5),
            pw.Text(value,
                style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                    color: color)),
          ],
        ),
      ),
    );
  }

  static pw.Widget _buildBatchTable(List<BatchPerformanceRow> batches) {
    return pw.Table(
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(2),
        3: const pw.FlexColumnWidth(2),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(
            color: primaryColor,
            borderRadius: pw.BorderRadius.vertical(top: pw.Radius.circular(4)),
          ),
          children: [
            _headerCell('BATCH ID'),
            _headerCell('REVENUE'),
            _headerCell('COSTS'),
            _headerCell('NET PROFIT'),
          ],
        ),
        ...batches.asMap().entries.map((entry) {
          final i = entry.key;
          final b = entry.value;
          final isEven = i % 2 == 0;
          return pw.TableRow(
            decoration: pw.BoxDecoration(
                color: isEven ? PdfColors.white : PdfColors.grey50),
            children: [
              _dataCell(b.batchNumber),
              _dataCell(CurrencyFormatter.format(b.revenue)),
              _dataCell(CurrencyFormatter.format(b.costs)),
              _dataCell(CurrencyFormatter.format(b.netProfit),
                  color: b.netProfit >= 0 ? PdfColors.green : PdfColors.red),
            ],
          );
        }),
      ],
    );
  }

  static pw.Widget _buildBatchHeader(BatchFinancials batch) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: const pw.BoxDecoration(
        color: primaryColor,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('BATCH PERFORMANCE REPORT',
                  style: pw.TextStyle(color: PdfColors.grey300, fontSize: 8)),
              pw.Text(batch.batchId,
                  style: pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold)),
            ],
          ),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 5),
            decoration: pw.BoxDecoration(
              color: secondaryColor,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Text(batch.status.name.toUpperCase(),
                style: pw.TextStyle(
                    color: PdfColors.white,
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 10)),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildBatchDetails(BatchFinancials batch) {
    return pw.Row(
      children: [
        _detailItem('Initial Count', batch.initialCount.toString()),
        _detailItem('Mortality', '${batch.totalMortality} (${batch.mortalityRate.toStringAsFixed(1)}%)'),
        _detailItem('Survival Rate', '${batch.survivalRate.toStringAsFixed(1)}%'),
        _detailItem('ROI', '${batch.roi.toStringAsFixed(1)}%', color: secondaryColor),
      ],
    );
  }

  static pw.Widget _detailItem(String label, String value, {PdfColor? color}) {
    return pw.Expanded(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label, style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
          pw.Text(value, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: color ?? textColor)),
        ],
      ),
    );
  }

  static pw.Widget _buildExpenseTable(BatchFinancials batch) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('EXPENSE BREAKDOWN',
            style: pw.TextStyle(
                fontSize: 10, fontWeight: pw.FontWeight.bold, color: primaryColor)),
        pw.SizedBox(height: 10),
        pw.Table(
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(
                border: pw.Border(bottom: pw.BorderSide(color: primaryColor, width: 1)),
              ),
              children: [
                _headerCell('Category', color: primaryColor),
                _headerCell('Amount', color: primaryColor, align: pw.TextAlign.right),
              ],
            ),
            ...batch.categoryBreakdown.entries.map((e) => pw.TableRow(
                  children: [
                    _dataCell(e.key.name.toUpperCase()),
                    _dataCell(CurrencyFormatter.format(e.value), align: pw.TextAlign.right),
                  ],
                )),
          ],
        ),
      ],
    );
  }

  static pw.Widget _headerCell(String text, {PdfColor color = PdfColors.white, pw.TextAlign align = pw.TextAlign.left}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(10),
      child: pw.Text(text,
          textAlign: align,
          style: pw.TextStyle(
              color: color, fontWeight: pw.FontWeight.bold, fontSize: 10)),
    );
  }

  static pw.Widget _dataCell(String text, {PdfColor? color, pw.TextAlign align = pw.TextAlign.left}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(10),
      child: pw.Text(text,
          textAlign: align,
          style: pw.TextStyle(color: color ?? textColor, fontSize: 10)),
    );
  }
}
